---
kind: Template
apiVersion: v1
metadata:
 name: capstone2020
 annotations:
 description: Deployment template for a nodejs server and postgres db.
 tags: node
 iconClass: icon-node
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: capstone2020
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    generation: 2
    labels:
      app: capstone2020
  spec:
    replicas: 2
    selector:
      app: capstone2020
      deploymentconfig: capstone2020
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        labels:
          app: capstone2020
          deploymentconfig: capstone2020
      spec:
        containers:
        - image: ''
          dnsPolicy: ClusterFirst
          imagePullPolicy: Always
          name: capstone2020
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - capstone2020
          from:
            kind: ImageStreamTag
            name: 'capstone2020-builder:${VERSION}'
        type: ImageChange
- kind: Service
  apiVersion: v1
  metadata:
    name: capstone2020
    annotations:
      description: Exposes and load balances the application pods
    labels:
      app: capstone2020
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: capstone2020
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: 'true'
    labels:
      app: capstone2020
    name: capstone2020
  spec:
    host: capstone2020-${NAMESPACE}.pathfinder.gov.bc.ca
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: capstone2020
      weight: 100
    wildcardPolicy: None
parameters:
- name: VERSION
  required: true
- name: NAMESPACE
  required: true


